USE customer_behavior;
GO
select * from dbo.customer

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as total_revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?


select customer_id, 
discount_applied, 
purchase_amount
from dbo.customer
where  purchase_amount > (select AVG(purchase_amount)
						  from dbo.customer)
and  discount_applied = 'YES'

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5  [item_purchased], avg([review_rating]) as avg_rating
from dbo.customer
group by [item_purchased]
order by avg(review_rating) desc

-- Q4. Compare the average purchase amount between Standard and Express shipping types.
select * from dbo.customer
select [shipping_type], AVG([purchase_amount]) as avg_purchase_amt
from dbo.customer
group by [shipping_type]
having shipping_type = 'Express'
or shipping_type = 'Standard' 

select [shipping_type], AVG([purchase_amount]) as avg_purchase_amt
from dbo.customer
where shipping_type in ('Express','Standard') 
group by [shipping_type]

-- Q5. Do subscribed customers spend more than non-subscribed customers?
select [subscription_status],
COUNT(customer_id) as total_customers,
SUM(purchase_amount) as total_spend,
AVG(purchase_amount) as avg_spend
from dbo.customer
group by [subscription_status]
order by total_spend, avg_spend asc


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from dbo.customer

SELECT TOP 5
    [item_purchased],
    COUNT(*) AS total_purchases,
    SUM(
        CASE 
            WHEN [discount_applied] = 'YES' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,
    (
        SUM(
            CASE 
                WHEN discount_applied = 'YES' THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*)
    ) AS discount_percentage
FROM dbo.customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on number of previous purchases
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases <= 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.customer
)
SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM customer_type
GROUP BY customer_segment;



-- Q8. What are the top 3 most purchased products within each category?
WITH product_counts AS (
    SELECT
        [Category],
        [item_purchased],
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY [Category]
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM dbo.customer
    GROUP BY [Category], [item_purchased]
)
SELECT
    Category,
    [item_purchased],
    purchase_count
FROM product_counts
WHERE rn <= 3;


--Q9. Are repeat buyers (>5 previous purchases) also likely to subscribe?
SELECT
    [subscription_status],
    COUNT(*) AS customer_count
FROM dbo.customer
WHERE [previous_purchases] > 5
GROUP BY [subscription_status];

-- Q10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM([purchase_amount]) AS total_revenue
FROM dbo.customer
GROUP BY age_group
ORDER BY total_revenue DESC;
